[package]
homepage = "https://github.com/nff747"
name = "wasm-llm-parser"
version = "0.1.0"
edition = "2021"
authors = ["nff747 <https://github.com/nff747>"]
description = "A tiny Rust->WASM drop-in parser that strips markdown and extracts code blocks for LLMs."
license = "MIT"
repository = "https://github.com/nff747/wasm-llm-parser"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-bulk-memory"]
